<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Simple linear regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>RMS2</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_tidyverse.html">RMS2 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Regression models
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="01_slr.html">1/1: Simple linear regression</a>
    </li>
    <li>
      <a href="02_mlr.html">1/2: Multiple regression basics</a>
    </li>
    <li>
      <a href="03_mlr_int.html">1/3: Interactions</a>
    </li>
    <li>
      <a href="04_mlr_assumpt.html">1/4: Assumptions and diagnostics</a>
    </li>
    <li>
      <a href="05_mlr_eval.html">1/5: Model fit, model comparison, and model selection</a>
    </li>
    <li class="dropdown-header">1/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Models for experimental data
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="07_anova.html">1/7: ANOVA and contrasts</a>
    </li>
    <li>
      <a href="08_factorial_anova.html">1/8: Factorial ANOVA</a>
    </li>
    <li>
      <a href="09_repeated_measures.html">1/9: Repeated measures</a>
    </li>
    <li>
      <a href="10_surveys_pca.html">1/10: Surveys and  PCA</a>
    </li>
    <li>
      <a href="11_fa.html">1/11: Exploratory factor analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Extra
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="intro_r_rstudio.html">Getting started with R &amp; RStudio</a>
    </li>
    <li>
      <a href="extra_writeup.html">Example Write-up</a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Simple linear regression</h1>

</div>


<p>This set of exercises gradually introduces simple linear regression. It starts by stating the research question of interest, performing an exploratory analysis of the data, fitting the model, and understanding the components of the fitted model.</p>
<p>For those of you who have previously taken a first course in data analysis or statistics, such as RMS1, this will be a refresher.</p>
<div id="research-question" class="section level1">
<h1>Research question</h1>
<p>Let’s imagine a study into income disparity for workers in a local authority. We might carry out interviews and find that there is a link between the level of education and an employee’s income. Those with more formal education seem to be better paid.
Now we wouldn’t have time to interview everyone who works for the local authority so we would have to interview a sample, say 10%.</p>
<p>In this lab we will use the riverview data (see below) to examine whether education level is related to income among the employees working for the city of Riverview, a hypothetical midwestern city in the US.</p>
<div class="optional-begin">
Data: riverview.csv. Click the plus to expand →<span id="opt-start-1" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-1&#39;, &#39;opt-start-1&#39;)"></span>
</div>
<div class="optional-body" id = "opt-body-1" style="display: none;">


<p><strong>Download link</strong></p>
<p><a href="https://uoepsy.github.io/data/riverview.csv" target="_blank">Download the data here</a></p>
<p><strong>Description</strong></p>
<p>The riverview data come from <span class="citation">Lewis-Beck and Lewis-Beck (<a href="#ref-Lewis-Beck2015" role="doc-biblioref">2015</a>)</span> and contain five attributes collected from a random sample of <span class="math inline">\(n=32\)</span> employees working for the city of Riverview, a hypothetical midwestern city in the US. The attributes include:</p>
<ul>
<li><code>education</code>: Years of formal education</li>
<li><code>income</code>: Annual income (in thousands of U.S. dollars)</li>
<li><code>seniority</code>: Years of seniority</li>
<li><code>gender</code>: Employee’s gender</li>
<li><code>male</code>: Dummy coded gender variable (0 = Female, 1 = Male)</li>
<li><code>party</code>: Political party affiliation</li>
</ul>
<p><strong>Preview</strong></p>
<p>The first six rows of the data are:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
education
</th>
<th style="text-align:center;">
income
</th>
<th style="text-align:center;">
seniority
</th>
<th style="text-align:center;">
gender
</th>
<th style="text-align:center;">
male
</th>
<th style="text-align:center;">
party
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
37.449
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
Democrat
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
26.430
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
Independent
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
47.034
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
Democrat
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
34.182
</td>
<td style="text-align:center;">
16
</td>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
Independent
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
25.479
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
Republican
</td>
</tr>
<tr>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
46.488
</td>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
Democrat
</td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
<p><br></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Load the required libraries and import the riverview data into a variable named <code>riverview</code>.</p>
<p><em><strong>Tip:</strong>
The data file is called ‘riverview.csv’. Hence, the data are in comma separated value (csv) format and the appropriate <code>tidyverse</code> function is <code>read_csv()</code>.</em></p>
<p><strong>Steps:</strong></p>
<ol style="list-style-type: decimal">
<li>Load the tidyverse library</li>
<li>Read the data into R using <code>read_csv()</code></li>
<li>Check that everything went correctly by inspecting the top 6 rows of the data with the function <code>head()</code>.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-2" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-2&#39;, &#39;sol-start-2&#39;)"></span>
</div>
<div id="sol-body-2" class="solution-body" style="display: none;">
<p>Load the tidyverse library:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>Read the data into R:</p>
<pre class="r"><code>riverview &lt;- read_csv(file = &quot;https://uoepsy.github.io/data/riverview.csv&quot;)</code></pre>
<p>Check for reading errors by inspecting the first six rows of the data:</p>
<pre class="r"><code>head(riverview)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   education income seniority gender  male party      
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;      
## 1         8   37.4         7 male       1 Democrat   
## 2         8   26.4         9 female     0 Independent
## 3        10   47.0        14 male       1 Democrat   
## 4        10   34.2        16 female     0 Independent
## 5        10   25.5         1 female     0 Republican 
## 6        12   46.5        11 female     0 Democrat</code></pre>
</div>
<p class="solution-end">
</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data exploration</h1>
<div id="marginal-distributions" class="section level2">
<h2>Marginal distributions</h2>
<p>Typical steps when examining the marginal distribution of a numeric variable are:</p>
<ol style="list-style-type: decimal">
<li><p><em>Visualise the distribution of the variable</em>.
You could use, for example, <code>geom_density()</code> for a density plot or <code>geom_histogram()</code> for a histogram.</p></li>
<li><p><em>Comment on the shape of the distribution</em>.
Look at the shape, centre and spread of the distribution.
Is it symmetric or skewed? Is it unimodal or bimodal?</p></li>
<li><p><em>Identify any unusual observations</em>.
Do you notice any extreme observations?</p></li>
</ol>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of employee incomes.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-3" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-3&#39;, &#39;sol-start-3&#39;)"></span>
</div>
<div id="sol-body-3" class="solution-body" style="display: none;">
<p>We can plot the marginal distribution of employee incomes as a density curve, and add a boxplot underneath to check for the presence of outliers.</p>
<pre class="r"><code>ggplot(data = riverview, aes(x = income)) +
  geom_density() +
  geom_boxplot(width = 1/300) +
  labs(x = &quot;Income (in thousands of U.S. dollars)&quot;, 
       y = &quot;Probability density&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-5"></span>
<img src="01_slr_files/figure-html/unnamed-chunk-5-1.png" alt="Density plot and boxplot of employee incomes." width="70%" />
<p class="caption">
Figure 1: Density plot and boxplot of employee incomes.
</p>
</div>
<p>The plot suggests that the distribution of employee incomes is unimodal and most of the incomes are between roughly $45,000 and $70,000.
The smallest income in the sample is about $25,000 and the largest income is over $80,000. (We could find the exact values using the <code>summary()</code> function).
This suggests there is a fair amount of variation in the data.
Furthermore, the boxplot does not highlight any outliers in the data.</p>
<p>To further summarize the distribution, it is typical to compute and report numerical summary statistics such as the mean and standard deviation. One way to compute these values is to use the <code>summary()</code> function from the <code>tidyverse</code> library:</p>
<pre class="r"><code>riverview %&gt;% 
  summarize(
    M = mean(income), 
    SD = sd(income)
    )</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  53.7  14.6</code></pre>
<p>Following the exploration above, we can describe this variable as follows:</p>
<div class="int">
<p>The marginal distribution of income is unimodal with a mean of approximately $53,700. There is variation in employees’ salaries (SD = $14,553).</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Display and describe the marginal distribution of education level.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-4" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-4&#39;, &#39;sol-start-4&#39;)"></span>
</div>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p>We can visualise the marginal distribution of education level using a density curve, and add a boxplot underneath to check for the presence of outliers.</p>
<pre class="r"><code>ggplot(data = riverview, aes(x = education)) +
  geom_density() +
  geom_boxplot(width = 1/100) +
  labs(x = &quot;Education (in years)&quot;, 
       y = &quot;Probability density&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-7"></span>
<img src="01_slr_files/figure-html/unnamed-chunk-7-1.png" alt="Density plot and boxplot of employee education levels." width="70%" />
<p class="caption">
Figure 2: Density plot and boxplot of employee education levels.
</p>
</div>
<p>Below are the summary statistics for the employees’ level of education:</p>
<pre class="r"><code>riverview %&gt;%
  summarize(
    M = mean(education),
    SD = sd(education)
    )</code></pre>
<pre><code>## # A tibble: 1 x 2
##       M    SD
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    16  4.36</code></pre>
<p>Again, we might write:</p>
<div class="int">
<p>The marginal distribution of education is unimodal with a mean of 16 years. There is variation in employees’ level of education (SD = 4.4 years).</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="relationship-between-variables" class="section level2 unnumbered">
<h2>Relationship between variables</h2>
<p>After examining the marginal distributions of the variables of interest in the analysis, we typically move on to examining relationships between the variables.</p>
<p>When describing the relationship between two numeric variables, we typically look at their scatterplot and comment on four characteristics of the relationship:</p>
<ol style="list-style-type: decimal">
<li>The <em>direction</em> of the association indicates whether large values of one variable tend to go with large values of the other (positive association) or with small values of the other (negative association).</li>
<li>The <em>form</em> of association refers to whether the relationship between the variables can be summarized well with a straight line or some more complicated pattern.</li>
<li>The <em>strength</em> of association entails how closely the points fall to a recognizable pattern such as a line.</li>
<li><em>Unusual observations</em> that do not fit the pattern of the rest of the observations and which are worth examining in more detail.</li>
</ol>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Create a scatterplot of income and education level.</p>
<p>Describe the relationship between income and level of education among the employees in the sample.</p>
<p><em><strong>Hint:</strong> To comment on the strength of a linear association, compute the correlation coefficient with the <code>cor()</code> function.</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-5" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-5&#39;, &#39;sol-start-5&#39;)"></span>
</div>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>We are trying to investigate how income varies when varying years of formal education.
Hence income is the dependent variable (on the y-axis), and education is the independent variable (on the x-axis).</p>
<pre class="r"><code>ggplot(data = riverview, aes(x = education, y = income)) +
  geom_point(alpha = 0.5) +
  labs(x = &quot;Education (in years)&quot;, 
       y = &quot;Income (in thousands of U.S. dollars)&quot;)</code></pre>
<div class="figure" style="text-align: center"><span id="fig:riverview-scatterplot"></span>
<img src="01_slr_files/figure-html/riverview-scatterplot-1.png" alt="The relationship between employees' education level and income." width="70%" />
<p class="caption">
Figure 3: The relationship between employees’ education level and income.
</p>
</div>
<p>To comment on the strength of the linear association we compute the correlation coefficient:</p>
<pre class="r"><code>riverview %&gt;%
  select(education, income) %&gt;%
  cor()</code></pre>
<pre><code>##           education    income
## education 1.0000000 0.7947847
## income    0.7947847 1.0000000</code></pre>
<p>that is,
<span class="math display">\[
r_{Education,\ Income} = 0.79
\]</span></p>
<p>We might write:</p>
<div class="int">
<p>There is a strong positive linear relationship between education level and income for the employees in the sample.
High incomes tend to be observed, on average, with more years of formal education.
The scatterplot does not highlight any outliers.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
</div>
<div id="model-specification-and-fitting" class="section level1">
<h1>Model specification and fitting</h1>
<p>The scatterplot highlights a linear relationship, where the data points are scattered around an underlying linear pattern with a roughly-constant spread as x varies.</p>
<p>Hence, we will try to fit a simple (= one x variable only) linear regression model:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon \quad \text{where} \quad \epsilon \sim N(0, \sigma) \text{ independently}
\]</span></p>
<p>where “<span class="math inline">\(\epsilon \sim N(0, \sigma) \text{ independently}\)</span>” means that the errors are normally scattered around the line with mean zero and constant spread as x varies.</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Fit the linear model to the sample data using the <code>lm()</code> function and name the output <code>mdl</code>.</p>
<p>Write down the equation of the fitted line.</p>
<p><em><strong>Hint:</strong></em>
<em>The syntax of the <code>lm()</code> function is: </em></p>
<pre><code>lm(&lt;response variable&gt; ~ 1 + &lt;explanatory variable&gt;, data = &lt;dataframe&gt;)</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-6" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-6&#39;, &#39;sol-start-6&#39;)"></span>
</div>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>The fitted model can be written as
<span class="math display">\[
\widehat{Income} = \hat \beta_0 + \hat \beta_1 \ Education
\]</span>
or
<span class="math display">\[
\widehat{Income} = \hat \beta_0 \cdot 1 + \hat \beta_1 \cdot Education
\]</span></p>
<p>When we specify the linear model in R, we include after the tilde sign, <code>~</code>, the variables that appear to the right of the <span class="math inline">\(\hat \beta\)</span>s. That’s why the 1 is included.</p>
<p>As the variables are in the <code>riverview</code> dataframe, we would write:</p>
<pre class="r"><code>mdl &lt;- lm(income ~ 1 + education, data = riverview)
mdl</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Coefficients:
## (Intercept)    education  
##      11.321        2.651</code></pre>
<p>Note that by calling the name of the fitted model, <code>mdl</code>, you can see the estimated regression coefficients <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span>. The fitted line is:
<span class="math display">\[
\widehat{Income} = 11.32 + 2.65 \ Education \\
\]</span></p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>Explore the following equivalent ways to obtain the estimated regression coefficients — that is, <span class="math inline">\(\hat \beta_0\)</span> and <span class="math inline">\(\hat \beta_1\)</span> — from the fitted model:</p>
<ul>
<li><code>mdl</code></li>
<li><code>mdl$coefficients</code></li>
<li><code>coef(mdl)</code></li>
<li><code>coefficients(mdl)</code></li>
<li><code>summary(mdl)</code> and look at the “Estimate” column</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-7" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-7&#39;, &#39;sol-start-7&#39;)"></span>
</div>
<div id="sol-body-7" class="solution-body" style="display: none;">
<p>To obtain the estimated regression coefficients you can either:</p>
<ul>
<li>type <code>mdl</code>, i.e. simply invoke the name of the fitted model;</li>
<li>type <code>mdl$coefficients</code>;</li>
<li>use the <code>coef(mdl)</code> function;</li>
<li>use the <code>coefficients(mdl)</code> function;</li>
<li>use the <code>summary(mdl)</code> function and look under the “Estimate” column.</li>
</ul>
<p>The estimated parameters returned by the above methods are all equivalent. However, <code>summary()</code> returns more information and you need to look under the column “Estimate”.</p>
<pre class="r"><code>mdl</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Coefficients:
## (Intercept)    education  
##      11.321        2.651</code></pre>
<pre class="r"><code>mdl$coefficients</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>coef(mdl)</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>coefficients(mdl)</code></pre>
<pre><code>## (Intercept)   education 
##   11.321379    2.651297</code></pre>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The estimated intercept is <span class="math inline">\(\hat \beta_0 = 11.32\)</span> and the estimated slope is <span class="math inline">\(\hat \beta_1 = 2.65\)</span>.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Interpret the estimated intercept and slope in the context of the question of interest.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-8" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-8&#39;, &#39;sol-start-8&#39;)"></span>
</div>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>We can interpret the estimated intercept as follows,</p>
<div class="int">
<p>The estimated average income associated to zero years of formal education is $11,321.</p>
</div>
<p>For the estimated slope we might write,</p>
<div class="int">
<p>The estimated increase in average income associated to a one year increase in education is $2,651.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Plot the data and the fitted regression line. To do so:</p>
<ul>
<li>Extract the estimated regression coefficients e.g. via <code>betas &lt;- coef(mdl)</code></li>
<li>Extract the first entry of <code>betas</code> via <code>betas[1]</code></li>
<li>Extract the second entry of <code>betas</code> via <code>betas[2]</code></li>
<li>Provide the intercept and slope to the function</li>
</ul>
<pre><code>geom_abline(intercept = &lt;intercept&gt;, slope = &lt;slope&gt;)</code></pre>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-9" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-9&#39;, &#39;sol-start-9&#39;)"></span>
</div>
<div id="sol-body-9" class="solution-body" style="display: none;">
<p>The function <code>coef(mdl)</code> returns a <em>vector</em>: that is, a sequence of numbers all of the same type.
To get the first element of the sequence you append <code>[1]</code>, and <code>[2]</code> for the second.</p>
<p>We can plot the model as follows:</p>
<pre class="r"><code>betas &lt;- coef(mdl)
intercept &lt;- betas[1]
slope &lt;- betas[2]

ggplot(data = riverview, aes(x = education, y = income)) +
  geom_point(alpha = 0.5) +
  geom_abline(intercept = intercept, slope = slope, 
              color = &#39;blue&#39;, size = 1) + 
  labs(x = &quot;Education (in years)&quot;, 
       y = &quot;Income (in thousands of U.S. dollars)&quot;)</code></pre>
<p><img src="01_slr_files/figure-html/unnamed-chunk-12-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
</div>
<div id="fitted-and-predicted-values" class="section level1">
<h1>Fitted and predicted values</h1>
<p>To compute the model-predicted values for the data in the sample:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;)</code></li>
<li><code>fitted(&lt;fitted model&gt;)</code></li>
<li><code>fitted.values(&lt;fitted model&gt;)</code></li>
<li><code>mdl$fitted.values</code></li>
</ul>
<pre class="r"><code>predict(mdl)</code></pre>
<pre><code>##        1        2        3        4        5        6        7        8 
## 32.53175 32.53175 37.83435 37.83435 37.83435 43.13694 43.13694 43.13694 
##        9       10       11       12       13       14       15       16 
## 43.13694 48.43953 48.43953 48.43953 51.09083 53.74212 53.74212 53.74212 
##       17       18       19       20       21       22       23       24 
## 53.74212 53.74212 56.39342 59.04472 59.04472 61.69601 61.69601 64.34731 
##       25       26       27       28       29       30       31       32 
## 64.34731 64.34731 64.34731 66.99861 66.99861 69.64990 69.64990 74.95250</code></pre>
<p>To compute model-predicted values for other data:</p>
<ul>
<li><code>predict(&lt;fitted model&gt;, newdata = &lt;dataframe&gt;)</code></li>
</ul>
<pre class="r"><code>education_query &lt;- tibble(education = c(11, 23))
predict(mdl, newdata = education_query)</code></pre>
<pre><code>##        1        2 
## 40.48564 72.30120</code></pre>
</div>
<div id="residuals" class="section level1">
<h1>Residuals</h1>
<p>The residuals represent the deviations between the actual responses and the predicted responses and can be obtained either as</p>
<ul>
<li><code>mdl$residuals</code>;</li>
<li><code>resid(mdl)</code>;</li>
<li><code>residuals(mdl)</code>;</li>
<li>computing them as the difference between the response and the predicted response.</li>
</ul>
<div class="question-begin">
Question 9
</div>
<div class="question-body">
<p>Use <code>predict(mdl)</code> to compute the fitted values and residuals. Mutate the <code>riverview</code> dataframe to include the fitted values and residuals as extra columns.</p>
<p>Assign to the following symbols the corresponding numerical values:</p>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = response variable for unit <span class="math inline">\(i = 3\)</span> in the sample data</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = fitted value for the third unit</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = the residual corresponding to the 5th unit.</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-10" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-10&#39;, &#39;sol-start-10&#39;)"></span>
</div>
<div id="sol-body-10" class="solution-body" style="display: none;">
<pre class="r"><code>riverview_fitted &lt;- riverview %&gt;%
  mutate(
    income_hat = predict(mdl),
    resid = income - income_hat
  )

head(riverview_fitted)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   education income seniority gender  male party       income_hat  resid
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
## 1         8   37.4         7 male       1 Democrat          32.5   4.92
## 2         8   26.4         9 female     0 Independent       32.5  -6.10
## 3        10   47.0        14 male       1 Democrat          37.8   9.20
## 4        10   34.2        16 female     0 Independent       37.8  -3.65
## 5        10   25.5         1 female     0 Republican        37.8 -12.4 
## 6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
<ul>
<li><span class="math inline">\(y_{3}\)</span> = 47.03</li>
<li><span class="math inline">\(\hat y_{3}\)</span> = 37.83</li>
<li><span class="math inline">\(\hat \epsilon_{5} = y_{5} - \hat y_{5}\)</span> = -12.36</li>
</ul>
</div>
<p class="solution-end">
</p>
</div>
<div id="inference-for-regression-coefficients" class="section level1">
<h1>Inference for regression coefficients</h1>
<p>Consider again the output of the <code>summary()</code> function:</p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>To quantify the amount of uncertainty in each estimated coefficient that is due to sampling variability, we use the standard error (SE) of the coefficient.
<em>Recall that a standard error gives a numerical answer to the question of how variable a statistic will be because of random sampling.</em></p>
<p>The standard errors are found in the column “Std. Error”. That is, the SE of the intercept is 6.1232, and the SE of the slope corresponding to the education variable is 0.3696.</p>
<p>In this example the slope, 2.651, has a standard error of 0.37. One way to envision this is as a distribution. Our best guess (mean) for the slope parameter is 2.651. The standard deviation of this distribution is 0.37, which indicates the precision (uncertainty) of our estimate.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-17"></span>
<img src="01_slr_files/figure-html/unnamed-chunk-17-1.png" alt="Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37." width="70%" />
<p class="caption">
Figure 4: Sampling distribution of the slope coefficient. The distribution is approximately bell-shaped with a mean of 2.651 and a standard error of 0.37.
</p>
</div>
<p>It shouldn’t surprise you that the reference distribution in this case is a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, where <span class="math inline">\(n\)</span> is the sample size.
Recall the main formulas for obtaining a confidence interval and a test-statistic:</p>
<div class="frame">
<p><strong>Test statistic</strong></p>
<p>A test statistic for the null hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> is
<span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE(\hat \beta_1)}
\]</span>
which follows a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</p>
<p><strong>Confidence interval</strong></p>
<p>A confidence interval for the population slope is
<span class="math display">\[
\hat \beta_1 \pm t^* \cdot SE(\hat \beta_1)
\]</span>
where <span class="math inline">\(t^*\)</span> denotes the critical value chosen from t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom for a desired <span class="math inline">\(\alpha\)</span> level of confidence.</p>
</div>
<div class="question-begin">
Question 10
</div>
<div class="question-body">
<p>Test the hypothesis that the population slope is zero — that is, that there is no linear association between income and education level in the population.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-11" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-11&#39;, &#39;sol-start-11&#39;)"></span>
</div>
<div id="sol-body-11" class="solution-body" style="display: none;">
<p>We calculate the test statistic
<span class="math display">\[
t = \frac{\hat \beta_1 - 0}{SE(\hat \beta_1)} = \frac{ 2.6513 - 0 }{0.3696} = 7.173
\]</span>
and compare it with the 5% critical value from a t-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom, which is:</p>
<pre class="r"><code>n &lt;- nrow(riverview)
tstar &lt;- qt(0.975, df = n - 2)
tstar</code></pre>
<pre><code>## [1] 2.042272</code></pre>
<p>As <span class="math inline">\(|t|\)</span> is much larger than <span class="math inline">\(t^*\)</span>, we reject then null hypothesis as have strong evidence against it.</p>
<p>The p-value, shown below, also confirms the conclusion.</p>
<pre class="r"><code>2 * (1 - pt(7.173, n - 2))</code></pre>
<pre><code>## [1] 5.561692e-08</code></pre>
<p>Please note that the same information was already contained in the row corresponding to the variable “education” in the output of <code>summary(mdl)</code>, which reported the t-statistic under <code>t value</code> and the p-value under <code>Pr(&gt;|t|)</code>:</p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>Before we interpret the results, recall that the p-value <code>5.56e-08</code> in the <code>Pr(&gt;|t|)</code> column simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>. This is a very small value, hence we will report it as &lt;.001 following the APA guidelines.</p>
<div class="int">
<p>We performed a t-test against the null hypothesis that education is not a significant predictor of income: <span class="math inline">\(t(30) = 7.173,\ p &lt; .001\)</span>, two-sided.
The large t-statistic leads to a very small p-value, meaning that we have strong evidence against the null hypothesis.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 11
</div>
<div class="question-body">
<p>Compute a confidence interval for the regression slope.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-12" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-12&#39;, &#39;sol-start-12&#39;)"></span>
</div>
<div id="sol-body-12" class="solution-body" style="display: none;">
<p>In the riverview example, for 95% confidence we have <span class="math inline">\(t^* = 2.04\)</span>:</p>
<pre class="r"><code>n &lt;- nrow(riverview)
tstar &lt;- qt(0.975, df = n - 2)
tstar</code></pre>
<pre><code>## [1] 2.042272</code></pre>
<p>The confidence interval is:</p>
<pre class="r"><code>beta1_ci &lt;- tibble(
  lower = 2.6513 - tstar * 0.3696,
  upper = 2.6513 + tstar * 0.3696,
)
beta1_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower upper
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  1.90  3.41</code></pre>
<p>In R it is easy to obtain the confidence intervals for the regression coefficients using the command <code>confint()</code>:</p>
<pre class="r"><code>confint(mdl, level = 0.95)</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) -1.183935 23.826693
## education    1.896425  3.406168</code></pre>
<p>The result is exactly the same (up to rounding errors) as the previous one.</p>
<p>We typically report our uncertainty in a statistic by providing <span class="math inline">\(\text{estimate} \pm t^* \cdot \text{SE}\)</span>. Here we would say that because of sampling variation, we are 95% confident that the slope is between 1.896 and 3.406. Interpreting this, we might say,</p>
<div class="int">
<p>For all Riverview city employees, each one-year difference in formal education is associated with a difference in income between $1,896 and $3,406, on average.</p>
</div>
<p>Similarly, we could express the uncertainty in the intercept <span class="math inline">\(\hat \beta_0\)</span> as:</p>
<div class="int">
<p>The average income for all Riverview city employees with zero years of education is between $-1184 and $23,827.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="partitioning-variation" class="section level1">
<h1>Partitioning variation</h1>
<p>We might ask ourselves if the model is useful. To quantify and assess model utility, we split the total variability of the response into two terms: the variability explained by the model plus the variability left unexplained in the residuals.</p>
<p><span class="math display">\[
\text{total variability in response = variability explained by model + unexplained variability in residuals}
\]</span></p>
<p>Each term is quantified by a sum of squares:</p>
<p><span class="math display">\[
\begin{aligned}
SS_{Total} &amp;= SS_{Model} + SS_{Residual} \\
\sum_{i=1}^n (y_i - \bar y)^2 &amp;= \sum_{i=1}^n (\hat y_i - \bar y)^2 + \sum_{i=1}^n (y_i - \hat y_i)^2
\end{aligned}
\]</span></p>
<div class="question-begin">
Question 12
</div>
<div class="question-body">
<p>What is the proportion of the total variability in incomes explained by the linear relationship with education level?</p>
<p><em><strong>Hint:</strong> The question asks to compute the value of <span class="math inline">\(R^2\)</span>.</em></p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-13" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-13&#39;, &#39;sol-start-13&#39;)"></span>
</div>
<div id="sol-body-13" class="solution-body" style="display: none;">
<p>The proportion of the total variability in incomes explained by the linear relationship with education level is given by R-squared.</p>
<p><strong>Option 1</strong></p>
<p>The R-squared coefficient is defined as:
<span class="math display">\[
R^2 = \frac{SS_{Model}}{SS_{Total}} = 1 - \frac{SS_{Residual}}{SS_{Total}}
\]</span></p>
<p>In R we can write:</p>
<pre class="r"><code>riverview_fitted &lt;- riverview %&gt;%
  mutate(
    income_hat = predict(mdl),
    resid = income - income_hat
  )
head(riverview_fitted)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   education income seniority gender  male party       income_hat  resid
##       &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;
## 1         8   37.4         7 male       1 Democrat          32.5   4.92
## 2         8   26.4         9 female     0 Independent       32.5  -6.10
## 3        10   47.0        14 male       1 Democrat          37.8   9.20
## 4        10   34.2        16 female     0 Independent       37.8  -3.65
## 5        10   25.5         1 female     0 Republican        37.8 -12.4 
## 6        12   46.5        11 female     0 Democrat          43.1   3.35</code></pre>
<pre class="r"><code>riverview_fitted %&gt;%
  summarise(
    SSModel = sum( (income_hat - mean(income))^2 ),
    SSTotal = sum( (income - mean(income))^2 ),
    RSquared = SSModel / SSTotal
  )</code></pre>
<pre><code>## # A tibble: 1 x 3
##   SSModel SSTotal RSquared
##     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1   4147.   6566.    0.632</code></pre>
<hr />
<p><strong>Option 2</strong></p>
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The output of <code>summary()</code> displays the R-squared value in the following line:</p>
<pre><code>Multiple R-squared:  0.6317</code></pre>
<p>For the moment, ignore “Adjusted R-squared”. We will come back to this later in the course.</p>
<hr />
<p><strong>Option 3</strong></p>
<p>We can perform an <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance or, in short, ANOVA.
It simply means that we are examining/partitioning the total variability of a response variable.</p>
<p>The <code>anova()</code> function returns the sum of squares of interest in the column <code>Sum Sq</code>:</p>
<pre class="r"><code>mdl_anova &lt;- anova(mdl)
mdl_anova</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: income
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## education  1 4147.3  4147.3  51.452 5.562e-08 ***
## Residuals 30 2418.2    80.6                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Consider the column <code>Sum Sq</code>.
The entry corresponding to <code>education</code> gives <span class="math inline">\(SS_{Model}\)</span> = 4147.3, as education is the explanatory variable. The entry corresponding to <code>Residuals</code> gives <span class="math inline">\(SS_{Residual}\)</span> = 2418.2.</p>
<pre class="r"><code># Because the column name Sum Sq has a space, 
# we need to wrap it with backticks
SSModel &lt;- mdl_anova$`Sum Sq`[1]
SSResidual &lt;- mdl_anova$`Sum Sq`[2]
SSTotal &lt;- SSModel + SSResidual

RSquared &lt;- SSModel / SSTotal
RSquared</code></pre>
<pre><code>## [1] 0.6316828</code></pre>
<hr />
<p><strong>Interpretation</strong></p>
<div class="int">
<p>Approximately 63% of the total variability in employee incomes is explained by the linear association with education level.</p>
</div>
</div>
<p class="solution-end">
</p>
</div>
<div id="model-utility-test" class="section level1">
<h1>Model utility test</h1>
<p>To test if the model is useful — that is, if the explanatory variable is a useful predictor of the response — we test the following hypotheses:</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \text{the model is ineffective, } \beta_1 = 0 \\
H_1 &amp;: \text{the model is effective, } \beta_1 \neq 0
\end{aligned}
\]</span></p>
<p>The relevant test-statistic is the F-statistic:</p>
<p><span class="math display">\[
\begin{split}
F = \frac{MS_{Model}}{MS_{Residual}} = \frac{SS_{Model} / 1}{SS_{Residual} / (n-2)}
\end{split}
\]</span></p>
<p>which compares the amount of variation in the response explained by the model to the amount of variation left unexplained in the residuals.</p>
<p>The sample F-statistic is compared to an F-distribution with <span class="math inline">\(df_{1} = 1\)</span> and <span class="math inline">\(df_{2} = n - 2\)</span> degrees of freedom.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="question-begin">
Question 13
</div>
<div class="question-body">
<p>Perform a model utility test at the 5% significance level, by computing the F-statistic using its definition.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-14" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-14&#39;, &#39;sol-start-14&#39;)"></span>
</div>
<div id="sol-body-14" class="solution-body" style="display: none;">
<pre class="r"><code>df1 &lt;- 1
df2 &lt;- nrow(riverview) - 2
f_star &lt;- qf(0.95, df1, df2)
f_star</code></pre>
<pre><code>## [1] 4.170877</code></pre>
<pre class="r"><code>model_utility &lt;- riverview_fitted %&gt;%
  summarise(
    SSModel = sum( (income_hat - mean(income))^2 ),
    SSResid = sum( resid^2 ),
    MSModel = SSModel / 1,
    MSResid = SSResid / df2,
    FObs = MSModel / MSResid
  )
model_utility</code></pre>
<pre><code>## # A tibble: 1 x 5
##   SSModel SSResid MSModel MSResid  FObs
##     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1   4147.   2418.   4147.    80.6  51.5</code></pre>
<div class="int">
<p>We performed an F-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45\)</span>.</p>
<p>As the observed <span class="math inline">\(F = 51.45\)</span> is much larger than the critical value <span class="math inline">\(F^* = 4.17\)</span>, we have strong evidence to reject the null hypothesis that the model is ineffective.</p>
</div>
<p><br>
Alternatively, we can compute the p-value:</p>
<pre class="r"><code>pvalue &lt;- 1 - pf(model_utility$FObs, df1, df2)
pvalue</code></pre>
<pre><code>## [1] 5.562116e-08</code></pre>
<p>The value <code>5.562116e-08</code> simply means <span class="math inline">\(5.56 \times 10^{-8}\)</span>, so it’s a really small number.</p>
<div class="int">
<p>We performed an F-test of model utility at the 5% significance level, where <span class="math inline">\(F(1,30) = 51.45, p&lt;.001\)</span>.</p>
<p>The p-value (&lt; .001) is much lower than the specified significance level, meaning that we have very strong evidence against the null hypothesis.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="optional-begin">
Optional: Another formula for the F-test. Click the plus to expand →<span id="opt-start-15" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-15&#39;, &#39;opt-start-15&#39;)"></span>
</div>
<div id="opt-body-15" class="optional-body" style="display: none;">
<p>There is an equivalent formula for the F-statistic of model utility. With some algebra, we can show that the F-test for model utility can be seen as testing if the fraction of variability in the response explained by the model is due to chance alone or not:
<span class="math display">\[
F = \frac{R^2 / 1}{(1 - R^2) / (n - 2) } = \frac{R^2 / df_{Model}}{(1 - R^2) / df_{Residual} }
\]</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)} 
= \frac{\frac{SS_{Model}}{SS_{Total}}}{\frac{SS_{Residual}}{SS_{Total}} \cdot \frac{1}{(n - 2)}} 
= \frac{R^2 / 1}{(1 - R^2) / (n - 2)}
\end{aligned}
\]</span></p>
</div>
<p class="optional-end">
</p>
<div class="question-begin">
Question 14
</div>
<div class="question-body">
<p>Look at the output of <code>summary(mdl)</code> and <code>anova(mdl)</code>.</p>
<p>For each output, identify the relevant information to conduct an F-test against the null hypothesis that the model is ineffective at predicting income using education level.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-16" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-16&#39;, &#39;sol-start-16&#39;)"></span>
</div>
<div id="sol-body-16" class="solution-body" style="display: none;">
<pre class="r"><code>summary(mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = income ~ 1 + education, data = riverview)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.809  -5.783   2.088   5.127  18.379 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  11.3214     6.1232   1.849   0.0743 .  
## education     2.6513     0.3696   7.173 5.56e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.978 on 30 degrees of freedom
## Multiple R-squared:  0.6317, Adjusted R-squared:  0.6194 
## F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<p>The relevant row is the following:</p>
<pre><code>F-statistic: 51.45 on 1 and 30 DF,  p-value: 5.562e-08</code></pre>
<hr />
<p>Instead, the <code>anova()</code> output is:</p>
<pre class="r"><code>anova(mdl)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: income
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## education  1 4147.3  4147.3  51.452 5.562e-08 ***
## Residuals 30 2418.2    80.6                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And the relevant entries are:</p>
<ul>
<li>the <code>Df</code> column, which contains the degrees of freedom;</li>
<li><code>F value = 51.452</code>, which is the F-statistic;</li>
<li><code>Pr(&gt;F) = 5.562e-08</code> = <span class="math inline">\(5.562 \times 10^{-8}\)</span>, which is the p-value.</li>
</ul>
<hr />
<p>We might write up the test results as,</p>
<div class="int">
<p>We performed an F-test for the overall significance of the regression, <span class="math inline">\(F(1, 30) = 51.45, p &lt; .001\)</span>.
The large F-statistic leads to a very small p-value (<span class="math inline">\(&lt;.001\)</span>), meaning that we have very strong evidence against the null hypothesis that the model is ineffective.</p>
<p>In other words, the data provide strong evidence that education is an effective predictor of income.</p>
</div>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 15
</div>
<div class="question-body">
<p>Consider the <code>F value</code> output of <code>anova(mdl)</code> and the <code>t value</code> for education returned by <code>summary(mdl)</code></p>
<pre><code>F value = 51.452
t value = 7.173</code></pre>
<p>Do you notice any relationship between the F-statistic for overall model utility and the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>?</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution <span id="sol-start-17" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-17&#39;, &#39;sol-start-17&#39;)"></span>
</div>
<div id="sol-body-17" class="solution-body" style="display: none;">
<p><strong>In simple linear regression only</strong>, the F-statistic for overall model significance is equal to the square of the t-statistic for <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</p>
<p>You can check that the squared t-statistic is equal, up to rounding error, to the F-statistic:
<span class="math display">\[
t^2 = F \\
7.173^2 = 51.452
\]</span></p>
<div class="optional-begin">
Optional: Equivalence of t-test for the slope and model utility F-test in SLR. Click the plus to expand →<span id="opt-start-18" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-18&#39;, &#39;opt-start-18&#39;)"></span>
</div>
<div id="opt-body-18" class="optional-body" style="display: none;">
<p>Here we will show the equivalence of the F-test for model effectiveness and t-test for the slope.</p>
<p>Recall the formula of the sum of squares due to the model. We will rewrite it in an equivalent form below:
<span class="math display">\[
\begin{aligned}
SS_{Model} &amp;= \sum_i (\hat y_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_0 + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\bar y - \hat \beta_1 \bar x + \hat \beta_1 x_i - \bar y)^2 \\
&amp;= \sum_i (\hat \beta_1 (x_i - \bar x))^2 \\
&amp;= \hat \beta_1^2 \sum_i (x_i - \bar x)^2
\end{aligned}
\]</span></p>
<p>The F-statistic is given by:
<span class="math display">\[
\begin{aligned}
F = \frac{SS_{Model} / 1}{SS_{Residual} / (n - 2)} 
= \frac{\hat \beta_1^2 \sum_i (x_i - \bar x)^2}{\hat \sigma^2} 
= \frac{\hat \beta_1^2 }{\hat \sigma^2 / \sum_i (x_i - \bar x)^2}
\end{aligned}
\]</span></p>
<p>Now recall the formula of the t-statistic,
<span class="math display">\[
t = \frac{\hat \beta_1}{SE(\hat \beta_1)} = \frac{\hat \beta_1}{\hat \sigma / \sqrt{\sum_i (x_i - \bar x)^2}}
\]</span></p>
<p>It is evident that the latter is obtained as the square root of the former.</p>
</div>
<p class="optional-end">
</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
<div id="refs" class="references">
<div id="ref-Lewis-Beck2015">
<p>Lewis-Beck, Colin, and Michael Lewis-Beck. 2015. <em>Applied Regression: An Introduction</em>. Vol. 22. Sage publications.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>
<span class="math inline">\(SS_{Total}\)</span> has <span class="math inline">\(n - 1\)</span> degrees of freedom as one degree of freedom is lost in estimating the population mean with the sample mean <span class="math inline">\(\bar{y}\)</span>.
<span class="math inline">\(SS_{Residual}\)</span> has <span class="math inline">\(n - 2\)</span> degrees of freedom. There are <span class="math inline">\(n\)</span> residuals, but two degrees of freedom are lost in estimating the intercept and slope of the line used to obtain the <span class="math inline">\(\hat y_i\)</span>s.
Hence, by difference, <span class="math inline">\(SS_{Model}\)</span> has <span class="math inline">\(n - 1 - (n - 2) = 1\)</span> degree of freedom.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
